name: 'O365 HideDownloadExtension Workflow'

on:
  push:
    paths: 
      - 'Online/glasswall-hide-download-ext/**'

  workflow_dispatch:
    paths: 
      - 'Online/glasswall-hide-download-ext/**'

env:
  SPPKG_FILE_NAME: 'glasswall-hide-download-ext.sppkg'

defaults:
  run:
    working-directory: './Online/glasswall-hide-download-ext'

jobs:
  build:
    name: 'Build Extension'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      
    - name: Use Node.js 10.x
      uses: actions/setup-node@v2.1.4
      with:
        node-version: 10.x
    
    - name: Run npm ci
      run: npm ci
    
    - name: Run npm i -g gulp
      run: sudo npm i -g gulp
      if: runner.os == 'macOS'
    
    - name: Bundle and package
      run: |
        gulp clean
        gulp bundle --ship
        gulp package-solution --ship    

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: HideDownloadExtension
        path: /home/runner/work/gp-sharepoint-plugins/gp-sharepoint-plugins/Online/glasswall-hide-download-ext/sharepoint/solution/

    

    - name: Microsoft 365 Login Status
      run: m365 status         

    - name: Microsoft 365 Logout
      run: m365 logout          

  deploy:
    needs: build
    name: 'Deploy GW-DEV'      
    if: contains(github.ref, '/main')
    runs-on: ubuntu-latest
    environment: GW-DEV

    steps:
      - name: 'Download artifacts'
        uses: actions/download-artifact@v2
        with:
          name: HideDownloadExtension
          path: /home/runner/work/gp-sharepoint-plugins/gp-sharepoint-plugins/Online/glasswall-hide-download-ext/sharepoint/solution/
    
      - name: Install M365 CLI
        run: sudo npm i -g @pnp/cli-microsoft365@next
      
      - name: Create PEM File for M365 Login
        id: write_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'm365auth.pem'
          encodedString: ${{ secrets.PEM_ENCODED }}

      - name: Microsoft 365 Login with Cert
        run: m365 login --authType certificate --certificateFile ${{ steps.write_file.outputs.filePath }} --appId ${{ secrets.AADAPPID }} --tenant ${{ secrets.TENANTID }}        
      
      - name: Microsoft 365 Login Status
        run: m365 status

      - name: Deploy Extension
        uses: pnp/action-cli-deploy@v2.0.0
        with:
          APP_FILE_PATH: '/home/runner/work/gp-sharepoint-plugins/gp-sharepoint-plugins/Online/glasswall-hide-download-ext/sharepoint/solution/${{env.SPPKG_FILE_NAME}}'
        # SITE_COLLECTION_URL: https://${{ secrets.tenant}}.sharepoint.com/${{secrets.catalogsite}}
          SKIP_FEATURE_DEPLOYMENT: true
          OVERWRITE: true
